### ISSUE TITLE
Implement `ControlPlane` controller for GCP provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-gcp#12]
Similar to how we have implemented the `ControlPlane` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/controller/controlplane) let's please now do it for GCP.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-gcp.yaml) the `ControlPlaneConfig` should look like this:

```yaml
apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
kind: ControlPlaneConfig
cloudControllerManager:
  zone: europe-west1
  featureGates:
    CustomResourceValidation: true
```

No `ControlPlaneStatus` needs to be implemented right now (not needed yet).
