### ISSUE TITLE
Implement `Infrastructure` controller for GCP provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-gcp#13]
Similar to how we have implemented the `Infrastructure` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/infrastructure) let's please now do it for GCP.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-gcp.yaml#L13-L18) the `InfrastructureConfig` should look like this:

```yaml
apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
# vpc:
#   name: some-existing-vpc-name
  internal: 10.250.112.0/22
  workers: 10.250.0.0/19
```

Based on the [current implementation](https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/gcp-infra/templates/_main.tf#L121-L135) the `InfrastructureStatus` should look like this:

```yaml
---
apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureStatus
networks:
  vpc:
    name: network-name
  subnets:
  - purpose: nodes
    name: my-subnet
  - purpose: internal
    name: other-subnet
serviceAccountEmail: serviceaccount@email
```

The current infrastructure creation/deletion implementation can be found [here](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/gcpbotanist/infrastructure.go). Please try to change as little as possible (with every change the risk that we break something increases!) and just move the code over into the extensions infrastructure actuator.
