### ISSUE TITLE
Invalid terraform config when more than 1 `.networks.cloudNAT.natIPNames` are specified

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#265]
**How to categorize this issue?**

/area quality
/kind bug
/priority 2
/platform gcp

**What happened**:

Cannot create an Infrastucture with multiple `.networks.cloudNAT.natIPNames`

**What you expected to happen**:

To be able to create an Infrastucture with multiple `.networks.cloudNAT.natIPNames` 

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply a Infrastructure with more than 1 `.networks.cloudNAT.natIPNames`

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  name: bar
  namespace: shoot--foo--bar
spec:
  providerConfig:
    apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      worker: 10.250.0.0/19
      cloudNAT:
        natIPNames:
        - name: manualnat1
        - name: manualnat2
  region: europe-west1
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  sshPublicKey: # [...]
  type: gcp
```

2. Make sure that `terraform apply` fails with

```

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unexpected comma after argument

  on tf/main.tf line 203, in output "nat_ips":
 203:   value = data.google_compute_address.manualnat1.address,data.google_compute_address.manualnat2.address

Argument definitions must be separated by newlines, not commas. An argument
definition must end with a newline.

```

- Gardener version (if relevant):
- Extension version: v1.16.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
