### ISSUE TITLE
Classify missing CloudNAT IPs as configuration error

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#309]
**How to categorize this issue?**

/area ops-productivity
/area quality
/kind bug
/priority 3
/platform gcp

**What happened**:
Infrastructure reconciliation does not check whether the given CloudNAT IP exists. In such case it yields a terraform error that is not intuitive.

**What you expected to happen**:
provider-gcp to perform a prerequisite check whether the given CloudNAT IP exist. In such case provider-gcp should return an appropriate error and should add the `ERR_CONFIGURATION_PROBLEM` error code.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with a CloudNAT IP that does not exist

```yaml
apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  workers: 10.250.0.0/16
cloudNAT:
   minPortsPerVM: 2048
  natIPNames:
  - name: missingone
```

2. Make sure that the Infrastructure reconciliation fails with:

```
 * Null value found in list
on tf/main.tf line 42, in resource "google_compute_router_nat" "nat":
42:   nat_ips                = [data.google_compute_address.<address_name>.self_link]
Null values are not allowed for this attribute value. 
```

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.18.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
