### ISSUE TITLE
Topology labels are missing for CSI provisioned PVs

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#316]
**How to categorize this issue?**

/area storage
/area control-plane
/kind bug
/priority 3
/platform gcp

**What happened**:
The PVs provisioned by the in-tree driver (K8s < 1.18) have the following topology labels:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  labels:
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
  name: pvc-af9ae9b1-9c66-4ab1-9464-0851a80046a4
```

PVs provisioned by CSI (K8s >= 1.18) don't have the corresponding topology labels:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
  name: pv--79c91a3f-8391-4698-b82f-6e85c2c4c877
```

Users report that external tools may depend on the PV topology labels - for example valero.

According to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/797 this issue should be fixed by upgrade of external-provisioner to v2.2.1. But I tried this in my local setup and even with external-provisioner@v2.2.2 the PVs are still missing the topology labels.

**What you expected to happen**:
CSI provisioned PV to be backwards compatible with the in-tree driver and to have the appropriate topology labels.

**How to reproduce it (as minimally and precisely as possible)**:

Sample manifest:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: claim

```

---

In-tree:

1. Create a Shoot with `.spec.kubernetes.version=1.17.17`

2. Apply the sample manifest from above

```
$ k apply -f ~/foo.yaml
```

3. Make sure that the PV has the topology labels

```
$ k get pv pvc-af9ae9b1-9c66-4ab1-9464-0851a80046a4 -o json | jq '.metadata.labels'
{
  "failure-domain.beta.kubernetes.io/region": "europe-west1",
  "failure-domain.beta.kubernetes.io/zone": "europe-west1-b"
}
```

---

CSI:

1. Create a Shoot with `.spec.kubernetes.version=1.18.20`

2. Apply the sample manifest from above

```
$ k apply -f ~/foo.yaml
```

3. Make sure that the PV is missing the topology labels

```
$ k get pv pv--79c91a3f-8391-4698-b82f-6e85c2c4c877 -o json | jq '.metadata.labels'
null
```

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.18.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
