### ISSUE TITLE
admission-gcp: Worker's `providerConfig.serviceAccount` is not properly validated

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-gcp#387]
**How to categorize this issue?**

/area quality
/kind bug
/platform gcp

**What happened**:
Currently admission-gcp allows the following WorkerConfig to be specified:
```yaml
          apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
          kind: WorkerConfig
          serviceAccount:
            scopes:
              - 'https://www.googleapis.com/auth/cloud-platform'
```

Note that the `serviceAccount.name` should be required and non-empty. See https://github.com/gardener/gardener-extension-provider-gcp/blob/d22d912b74bab5f6665783cadfd41c112a351d64/pkg/apis/gcp/validation/worker.go#L53-L55

Checking the admission-gcp codebase, it looks like we have the following gap:

https://github.com/gardener/gardener-extension-provider-gcp/blob/d22d912b74bab5f6665783cadfd41c112a351d64/pkg/admission/validator/shoot.go#L140-L151

Note that `ValidateWorkerConfig` func (that also validates the `serviceAccount` field) is only invoked when there are `dataVolumes` specified.

**What you expected to happen**:
The `serviceAccount` field of the WorkerConfig should be validated properly and should not depend whether the pool has `dataVolumes` or not.

**How to reproduce it (as minimally and precisely as possible)**:

1. Specify the WorkerConfig from above

```yaml
          apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
          kind: WorkerConfig
          serviceAccount:
            scopes:
              - 'https://www.googleapis.com/auth/cloud-platform'
```

2. Make sure this results in a MachineClass with the following spec

```yaml
    serviceAccounts:
    - email: ""
      scopes:
      - https://www.googleapis.com/auth/cloud-platform
```

3. machine-controller-manager validation fails. It cannot deal with such MachineClass:
```
E0214 15:53:11.178370       1 machine.go:326] Error occurred while decoding machine error for machine "shoot--foo--nubqciz45w-worker-rrpe0-z1-57764-vd6kl": machine codes error: code = [Internal] message = [Machine status "shoot--foo--nubqciz45w-worker-rrpe0-z1-57764-vd6kl" failed on decodeProviderSpecAndSecret: machine codes error: code = [Internal] message = [Error while validating ProviderSpec [spec.serviceAccounts[0].email: Invalid value: "": email address is of invalid format]]]
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.20.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
