### ISSUE TITLE
Consider dropping `zone` field in `controlPlaneConfig`

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener-extension-provider-gcp#541]
**What would you like to be added**:
While testing HA, with new HA clusters, I was wondering which purpose the `zone` field serves and whether we can drop it, because it gives the impression of a *dominant* zone, which "looks" like a contradiction to HA:
```
 provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-north1-a <-- ?
```

**Why is this needed**:
To reach full HA.
