### ISSUE TITLE
Enable CMEK Encrypted Shoot Worker Node Boot Disks

### ISSUE THREAD

**Issue by aabond** [gardener/gardener-extension-provider-gcp#564]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
We need the ability to deploy Gardener Shoot Clusters to GCP where the shoot worker node root volumes (node boot disk) are encrypted using Customer Managed Encryption Keys (CMEK).  It appears that we can configure additional PVCs to use CMEK by configuring an appropriate storage class.  This is our primary feature request.  

Additionally, once shoot clusters can be configured to be deployed with CMEK on the node boot disks, we'd like to also be able to deploy managed seeds that are also deployed with CMEK encrypted node boot disks.  

**Why is this needed**:
Customer requirements.

**Comment by aabond** [comment]
Hello @himanshu-kun ,

Thank you for putting together the suggested change.  

When you mentioned changing `kmsKeyName` to `disk-encryption-kms-key`, I figured I'd look and see what GCP called it in their gcloud CLI and terraform implementations.

In gcloud cli, they use the argument `--boot-disk-kms-key=BOOT_DISK_KMS_KEY` to specify the fully-qualified path to the key of interest.  They also have a `--csek-key-file=FILE` argument for Customer Supplied Encryption Key (CSEK) where you can supply the actual key contents.  If it's not too much extra work, I'm wondering if it may be worth adding this functionality while we're adding CMEK support.

Gcloud CLI Help:
```
       --boot-disk-kms-key=BOOT_DISK_KMS_KEY
          ID of the key or fully qualified identifier for the key. To set the
          kms-key attribute:
          ▸ provide the argument --boot-disk-kms-key on the command line.

          This flag argument must be specified if any of the other arguments in
          this group are specified.

     --csek-key-file=FILE
        Path to a Customer-Supplied Encryption Key (CSEK) key file that maps
        Compute Engine resources to user managed keys to be used when creating,
        mounting, or taking snapshots of disks.

        If you pass - as value of the flag, the CSEK is read from stdin. See
        https://cloud.google.com/compute/docs/disks/customer-supplied-encryption
        for more details.
```

In terraform, they use `kms_key_self_link` in the `boot_disk` block to specify the fully-qualified key path for CMEK.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#kms_key_self_link
kms_key_self_link - (Optional) The self_link of the encryption key that is stored in Google Cloud KMS to encrypt this disk. Only one of kms_key_self_link and disk_encryption_key_raw may be set.


They also have the CSEK alternative called `disk_encryption_key_raw`.  

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#disk_encryption_key_raw 
disk_encryption_key_raw - (Optional) A 256-bit [customer-supplied encryption key] (https://cloud.google.com/compute/docs/disks/customer-supplied-encryption), encoded in RFC 4648 base64 to encrypt this disk. Only one of kms_key_self_link and disk_encryption_key_raw may be set.

So it seems the naming for the boot disk encryption key is not exactly standard.  Since the StorageClass is already using `disk-encryption-kms-key`, I think I like your suggestion of using it instead of `kmsKeyName`.  If we additionally decide to add CSEK support, perhaps we use `disk-encryption-kms-key-file` as the attribute name and make it reference a Gardener Project Infrastructure secret.  

Please let me know if you have any other questions or concerns.  

Thanks,
Andrew

**Comment by elankath** [comment]
Updating the issue with discussion on requirements:

1. We support the configuration of a key (key ring name and key name) for worker pool disks - boot and additional disks.
1. We ensure that the worker pool node keeps working even/also after key rotation - creating a new version of the same key.
1. We do not have to support the case that a key (with all its versions) was deleted
    1.  This will cause the older Node will fail eventually.
1. We do not have to support disk re-encryption. User is expected to recreate them using the new key (or newer version).

**Comment by elankath** [comment]
Updating with the latest status of discussion, the proposal has been simplified to the following

```
workers:
  - name: worker-xoluy
    machine:
      type: n1-standard-4
    minimum: 1
    maximum: 2
    volume:
      size: 50Gi
      type: pd-standard
      encrypted: true
    dataVolumes:
      - name: alpha
        type: pd-balanced
        size: 25Gi
        encrypted: true
      - name: beta
        type: SCRATCH
        size: 25Gi
        encrypted: false
providerConfig:
  apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
    kind: WorkerConfig
    # kmsKeyName refers the default encryption key for
    # disks marked for encryption
    kmsKeyName: projects/projectId/locations/zoneName/keyRings/keyRingName/cryptoKeys/keyName
    serviceAccount:
        email: name@projectId.iam.gserviceaccount.com
 ```
