### ISSUE TITLE
Volume snapshotting does not work

### ISSUE THREAD

**Issue by suleymanakbas91** [gardener/gardener-extension-provider-gcp#73]
**What happened**:

I provisioned a Gardener GCP cluster with CSI storage driver, deployed a sample pod, and a sample PVC. Then, I created a VolumeSnapshotClass and a VolumeSnapshot to trigger snapshotting from the existing PVC. However, snapshotting didn't work. VolumeSnapshot's readyToUse field does not become true, and I don't see any related disk or snapshot on the GCP project.

**How to reproduce it (as minimally and precisely as possible)**:

Create a PVC and a Pod:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: source-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["touch /demo/data/sample-file.txt && sleep 3000"]
    volumeMounts:
    - name: source-data
      mountPath: /demo/data
  volumes:
  - name: source-data
    persistentVolumeClaim:
      claimName: source-pvc
      readOnly: false
```

Then, create a VolumeSnapshotClass and a VolumeSnapshot:

```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: default-snapshot-class
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot-source-pvc
spec:
  source:
    persistentVolumeClaimName: source-pvc
```

Check the VolumeSnapshot status:

`kubectl get volumesnapshot snapshot-source-pvc`

**Environment**:

- Gardener version (if relevant): v1.3.0
- Extension version:
- Kubernetes version (use `kubectl version`): 1.18.1
- Cloud provider or hardware configuration: GCP
- Others:
