### ISSUE TITLE
Support enabling nesting virtualization for nodes

### ISSUE THREAD

**Issue by anbrsap** [gardener/gardener-extension-provider-gcp#856]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/platform gcp

**What would you like to be added**:

[Enabling nested virtualization][gcp_enable_nested_virtualization] for GCP Compute Engine VMs provisioned as shoot cluster nodes should be supported.

It should be configurable for individual worker pools.

Example Shoot manifest fragment:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
…
spec:
  cloudProfileName: gcp
  …
  provider:
    type: gcp
    workers:
    - name: pool-1
      machine:
        type: n1-standard-4
        enableNestedVirtualization: true # <---
      …
    …
```

**Why is this needed**:

For enhanced security we need to run pods via the [Kata Containers][kata] container runtime. Kata Containers uses lightweight virtual machines, which require [KVM][kvm], which requires Intel VT or AMD-V support from the CPUs.

On GCP Compute Engine, (certain) VM instance types do support nested virtualization, but it is disabled by default and needs to be enabled explicitly when required. As gardener-extension-provider-gcp implements node creation on GCP Compute Engine, it should support enabling nested virtualization.

[gcp_enable_nested_virtualization]: https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling#enable_nested_virtualization_directly_on_a_new_vm
[kata]: https://katacontainers.io/
[kvm]: https://www.linux-kvm.org
