### ISSUE TITLE
Default VolumeSnapshotClass is missing

### ISSUE THREAD

**Issue by suleymanakbas91** [gardener/gardener-extension-provider-gcp#91]
**What would you like to be added**:

A default `VolumeSnapshotClass`.

**Why is this needed**:

[Volume Snapshot Class](https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/) describes the storage type for the Volume Snapshots just like the Storage Class for the Persistent Volumes. It would be great if the cluster comes with a default Volume Snapshot Class, so volume snapshotting would work out of the box.

**Comment by rfranzke** [comment]
Would you like to submit a PR for a proposal of such a default class?

**Comment by suleymanakbas91** [comment]
The class for GCP would be: 
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: snapshot-class
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
```

It's almost the same as the storage class. So, this should be a simple addition. Do we need a proposal for this?
